"""
Django settings for NewsPortal project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv,find_dotenv
import logging

logger = logging.getLogger('django')
logger = logging.getLogger('django.request')
logger = logging.getLogger('django.server')
logger = logging.getLogger('django.template')
logger = logging.getLogger('django.db.backends')
logger = logging.getLogger('django.security')


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'style' : '{',
    'formatters': {
        'simple': {
            'format': '%(levelname)s %(message)s',
            'datefmt': '%Y.%m.%d %H:%M:',
        },
        'info': {
            'format': '%(asctime)s % (levelname)s %(module)s %(message)s%',
            'datefmt': '%Y.%m.%d %H:%M:',
        },
        'warning': {
            'format': '%(asctime)s % (levelname)s % (pathname)s %(message)s%',
            'datefmt': '%Y.%m.%d %H:%M:',

        },
        'errors': {
            'format': '%(asctime)s % (levelname)s % (pathname)s %(message)s %(exc_info)s',
            'datefmt': '%Y.%m.%d %H:%M:',

        },
        'security': {
            'format': '%(asctime)s % (levelname)s % (module)s %(message)s',
            'datefmt': '%Y.%m.%d %H:%M:',

        }
    },

    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },

        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },

        'file_general':{
            'level':'INFO',
            'filters': ['require_debug_false'],
            'class':'logging.FileHandler',
            'formatter':'info',
            'filename':'logs/general.log'
        },

        'file_errors':{
            'level':'ERROR',
            'filters': ['require_debug_true'],
            'class':'logging.FileHandler',
            'formatter':'errors',
            'filename':'logs/errors.log',
        },

        'file_security':{
            'level':'WARNING',
            'filters': ['require_debug_true'],
            'class':'logging.FileHandler',
            'formatter':'security',
            'filename':'logs/security.log',
        },

        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
            'formatter': 'warning',
        }
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file_general'],
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console', 'file_errors', 'file_general', 'mail_admins'],
            'propagate': True,
        },

        'django.server': {
            'handlers': ['file_errors', 'mail_admins'],
            'propagate': True,
        },

        'django.template': {
            'handlers': ['file_errors'],
            'propagate': True,
        },

        'django.db.backends': {
            'handlers': ['file_errors'],
            'propagate': True,
        },

        'django.security': {
            'handlers': ['file_errors'],
            'propagate': True,
        }
    }
}


load_dotenv(find_dotenv())

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1']

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.flatpages',
    'news',
    'django_filters',
    'sign',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'django_apscheduler',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware'
]

ROOT_URLCONF = 'NewsPortal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'NewsPortal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_DIRS = [
    BASE_DIR / "static"
]

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/news/profile/'
LOGOUT_REDIRECT_URL = '/accounts/login/'


ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'

ACCOUNT_FORMS = {'signup': 'sign.models.CommonSignupForm'}

EMAIL_HOST ='smtp.yandex.ru'
EMAIL_PORT= 465
EMAIL_HOST_USER= os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD= os.getenv('EMAIL_HOST_PASSWORD')
EMAIL_USE_SSL=True
DEFAULT_FROM_EMAIL= os.getenv('DEFAULT_FROM_EMAIL')

EMAIL_BACKEND= 'django.core.mail.backends.smtp.EmailBackend'

APSCHEDULER_DATETIME_FORMAT="N j, Y, f:s a"
APSCHEDULER_RUN_NOW_TIMEOUT= 25

SITE_URL= 'http://127.0.0.1:8000'

CELERY_BROKER_URL = 'redis://:DSh61pvrgEJZ00A7r0cNZUUSkaTnGvmL@redis-13923.c325.us-east-1-4.ec2.cloud.redislabs.com:13923'
CELERY_RESULT_BACKEND = 'redis://:DSh61pvrgEJZ00A7r0cNZUUSkaTnGvmL@redis-13923.c325.us-east-1-4.ec2.cloud.redislabs.com:13923'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.path.join(BASE_DIR, 'cache_files'),
    }
}


